apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-sample-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpa-sample-api
  template:
    metadata:
      labels:
        app: hpa-sample-api
    spec:
      containers:
      - name: hpa-sample-api
        image: rajat1323/my-node-api:latest
        ports:
        - containerPort: 9999
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: hpa-sample-api-service
spec:
  type: LoadBalancer
  selector:
    app: hpa-sample-api
  ports:
  - protocol: TCP
    port: 9999
    targetPort: 9999
